# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Factorio Mod luacheck
      # You may pin to the exact commit or the version.
      # uses: Roang-zero1/factorio-mod-luacheck@36bc44e4fb0fc415e176e9e8f9f88e432d67bdae
        uses: Roang-zero1/factorio-mod-luacheck@v1.1.0
          
      - name: factorio-mod-upload
      # You may pin to the exact commit or the version.
      # uses: mchangrh/factorio-mod-upload@4bc4bf175a09d175d11727a5e23538c8b6bceea2
        uses: mchangrh/factorio-mod-upload@v1.0.0
        with:
          # Name of mod
            mod-name: "nuclear-explosion"
          
